export const symbolDefinitions = {
  S1_HORIZ: {
    level: 1,
    character: "一",
    recipe: null,
    sizeMultiplier: 1.0,
    eliminationPoints: 10,
    explosionRadiusUnits: 1.7,
    explosionEffectLevels: [1],
  },
  S1_VERT: {
    level: 1,
    character: "丨",
    recipe: null,
    sizeMultiplier: 1.0,
    eliminationPoints: 10,
    explosionRadiusUnits: 1.7,
    explosionEffectLevels: [1],
  },
  S1_SWEEP: {
    level: 1,
    character: "丿",
    recipe: null,
    sizeMultiplier: 1.0,
    eliminationPoints: 10,
    explosionRadiusUnits: 1.7,
    explosionEffectLevels: [1],
  },
  S2_CROSS: {
    level: 2,
    character: "十",
    recipe: ["S1_HORIZ", "S1_VERT"],
    sizeMultiplier: 1.15,
    eliminationPoints: 30,
    explosionRadiusUnits: 2.2,
    explosionEffectLevels: [1, 2],
  },
  S2_CLIFF: {
    level: 2,
    character: "厂",
    recipe: ["S1_HORIZ", "S1_SWEEP"],
    sizeMultiplier: 1.15,
    eliminationPoints: 30,
    explosionRadiusUnits: 2.2,
    explosionEffectLevels: [1, 2],
  },
  S2_PERSON: {
    level: 2,
    character: "亻",
    recipe: ["S1_VERT", "S1_SWEEP"],
    sizeMultiplier: 1.15,
    eliminationPoints: 30,
    explosionRadiusUnits: 2.2,
    explosionEffectLevels: [1, 2],
  },
  S3_STONE: {
    level: 3,
    character: "石",
    recipe: ["S2_CROSS", "S2_CLIFF"],
    sizeMultiplier: 1.3,
    eliminationPoints: 70,
    explosionRadiusUnits: 2.5,
    explosionEffectLevels: [1, 2, 3],
  },
  S3_TENPLUS: {
    level: 3,
    character: "什",
    recipe: ["S2_CROSS", "S2_PERSON"],
    sizeMultiplier: 1.3,
    eliminationPoints: 70,
    explosionRadiusUnits: 2.5,
    explosionEffectLevels: [1, 2, 3],
  },
  S3_CREATE: {
    level: 3,
    character: "作",
    recipe: ["S2_CLIFF", "S2_PERSON"],
    sizeMultiplier: 1.3,
    eliminationPoints: 70,
    explosionRadiusUnits: 2.5,
    explosionEffectLevels: [1, 2, 3],
  },
  S4_GRASS: {
    level: 4,
    character: "艹",
    recipe: ["S3_STONE", "S3_TENPLUS"],
    sizeMultiplier: 1.45,
    eliminationPoints: 150,
    explosionRadiusUnits: 2.8,
    explosionEffectLevels: [1, 2, 3, 4],
  },
  S4_STEM: {
    level: 4,
    character: "芈",
    recipe: ["S3_STONE", "S3_CREATE"],
    sizeMultiplier: 1.45,
    eliminationPoints: 150,
    explosionRadiusUnits: 2.8,
    explosionEffectLevels: [1, 2, 3, 4],
  },
  S4_BASE: {
    level: 4,
    character: "廾",
    recipe: ["S3_TENPLUS", "S3_CREATE"],
    sizeMultiplier: 1.45,
    eliminationPoints: 150,
    explosionRadiusUnits: 2.8,
    explosionEffectLevels: [1, 2, 3, 4],
  },
};

export const mandalaDefinitions = {
  S1_HORIZ: {
    mandalaConfig: {
      numPoints: 3,
      innerRadius: 0.0,
      spikeDistance: 0.8,
      leafType: 'both',
      curveAmount: 0.4,
      fillStyle: 'lines',
    },
  },
  S1_VERT: {
    mandalaConfig: {
      numPoints: 3,
      innerRadius: 0.0,
      spikeDistance: 0.8,
      leafType: 'left',
      curveAmount: 0.4,
      fillStyle: 'solid',
    },
  },
  S1_SWEEP: {
    mandalaConfig: {
      numPoints: 3,
      innerRadius: 0.0,
      spikeDistance: 0.8,
      leafType: 'both',
      curveAmount: 0.4,
      fillStyle: 'solid',
    },
  },
  S2_CROSS: {
    mandalaConfig: {
      numPoints: 4,
      innerRadius: 0.0,
      spikeDistance: 0.8,
      leafType: 'both',
      curveAmount: 0.4,
      fillStyle: 'solid',
    },
  },
  S2_CLIFF: {
    mandalaConfig: {
      numPoints: 4,
      innerRadius: 0.0,
      spikeDistance: 0.8,
      leafType: 'left',
      curveAmount: 0.4,
      fillStyle: 'solid',
    },
  },
  S2_PERSON: {
    mandalaConfig: {
      numPoints: 4,
      innerRadius: 0.0,
      spikeDistance: 0.8,
      leafType: 'both',
      curveAmount: 0.4,
      fillStyle: 'lines',
    },
  },
  S3_STONE: {
    mandalaConfig: {
      numPoints: 5,
      innerRadius: 0.0,
      spikeDistance: 0.8,
      leafType: 'both',
      curveAmount: 0.4,
      fillStyle: 'lines',
    },
  },
  S3_TENPLUS: {
    mandalaConfig: {
      numPoints: 5,
      innerRadius: 0.0,
      spikeDistance: 0.8,
      leafType: 'left',
      curveAmount: 0.4,
      fillStyle: 'solid',
    },
  },
  S3_CREATE: {
    mandalaConfig: {
      numPoints: 5,
      innerRadius: 0.0,
      spikeDistance: 0.8,
      leafType: 'both',
      curveAmount: 0.4,
      fillStyle: 'solid',
    },
  },
  S4_GRASS: {
    mandalaConfig: {
      numPoints: 6,
      innerRadius: 0.0,
      spikeDistance: 0.8,
      leafType: 'both',
      curveAmount: 0.4,
      fillStyle: 'lines',
    },
  },
  S4_STEM: {
    mandalaConfig: {
      numPoints: 6,
      innerRadius: 0.0,
      spikeDistance: 0.8,
      leafType: 'left',
      curveAmount: 0.4,
      fillStyle: 'solid',
    },
  },
  S4_BASE: {
    mandalaConfig: {
      numPoints: 6,
      innerRadius: 0.0,
      spikeDistance: 0.8,
      leafType: 'both',
      curveAmount: 0.4,
      fillStyle: 'solid',
    },
  },
};

export const L1_SYMBOLS = ["S1_HORIZ", "S1_VERT", "S1_SWEEP"];
